# Anti-nyangkut (Matikan OPcache)
opcache.enable=0
opcache.enable_cli=0

# Tampilkan eror untuk memudahkan development
display_errors=On
display_startup_errors=On
error_reporting=E_ALL

# Pengaturan opsional untuk upload file besar di CI4
upload_max_filesize=64M
post_max_size=64M
memory_limit=256M
