
# Anti-nyangkut untuk file HTML/CSS/JS/Gambar
EnableSendfile Off
EnableMMAP Off

# Arahkan Document Root Apache ke folder /public milik CI4
DocumentRoot /var/www/html/public

<Directory /var/www/html/public>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
